bin:common:logging: add REWIND to improve messages with spinner integration

diff --git a/bin/common/logging b/bin/common/logging
--- a/bin/common/logging
+++ b/bin/common/logging
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2124,SC203
+# shellcheck disable=SC2124,SC2034
 
 set -ueo pipefail
 
@@ -7,19 +7,25 @@ set -ueo pipefail
 
 LOGGING_IS_LOADED=1
 
-BOLD='\033[1m' RED='\033[1;31m' YELLOW='\033[0;33m' GREEN='\033[1;32m' NC='\033[0m'
+readonly \
+    REWIND='\r\033[K' \
+    BOLD='\033[1m' \
+    RED='\033[1;31m' \
+    YELLOW='\033[0;33m' \
+    GREEN='\033[1;32m' \
+    NC='\033[0m'
 
 log::error() {
-    echo -e "${RED}ERROR: ${0}:${FUNCNAME[1]}:${NC}" "$@" >&2
+    echo -e "${REWIND}${RED}ERROR: ${0}:${FUNCNAME[1]}:${NC}" "$@" >&2
     exit 1
 }
 
 log::warn() {
-    echo -e "${YELLOW}WARNING: ${0}:${FUNCNAME[1]}:${NC}" "$@"
+    echo -e "${REWIND}${YELLOW}WARNING: ${0}:${FUNCNAME[1]}:${NC}" "$@"
 }
 
 log::info() {
-    echo -e "${GREEN}INFO: ${0}:${FUNCNAME[1]}:${NC}" "$@"
+    echo -e "${REWIND}${GREEN}INFO: ${0}:${FUNCNAME[1]}:${NC}" "$@"
 }
 
 log::not_implemented() {
